### ISSUE TITLE
Empty database problems

### ISSUE THREAD

**Issue by bakape** [underr/lolinks#5]
Steps:
1. Start server with empty db
2. Load `/` and don't submit anything
3. Refresh page
You are now permanently receiving an error page, until the server is restarted. Can't find the cause. Probably related to the DB.

**Comment by underr** [comment]
That's weird, I'm really not having this problem.
When I refresh it works normally. 

Maybe f10f0ede76855c9c134a84f53e22d7d06aa299c will help you.

**Comment by underr** [comment]
Oh, now I can see it.

Yep, it's definitely a bug.

**Comment by underr** [comment]
It was my usual stupid logic

Fixed with the switch to knex at e20a5f8b8785f0b5ad47bee5f026ba2214cd9a61
